# Generated by Django 4.2 on 2023-04-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoconsulta', models.CharField(max_length=200)),
                ('tratamiento', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoconsulta', models.CharField(max_length=200)),
                ('medicamento', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('piso', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('peso', models.CharField(max_length=200)),
                ('Consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitales.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
                ('Expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitales.expediente')),
            ],
        ),
    ]
